### ISSUE TITLE
Got an exception while trying to connect to telegram API

### ISSUE THREAD

**Issue by SmartHome-rus** [fabianonline/OctoPrint-Telegram#101]
Hi,
Trying to setup the plugin to work, but getting this message in the settings menu:
_The current connection status is: Got an exception while trying to connect to telegram API: gettext() takes exactly 1 argument (2 given). Waiting 2 minutes before trying again._

And of cource messages are not working, bot is not responding.
Any ideas?

Thanks in advance!

**Comment by derpicknicker1** [comment]
The bot worked before?
Full debug log?

**Comment by SmartHome-rus** [comment]
@derpicknicker1 Seems to be an issue with my old bot. Just created new one and everything works now.

**Comment by derpicknicker1** [comment]
Excellent! I had a similar issue a while ago.

**Comment by Darkensen** [comment]
Same problem; same solution : recreate the bot
