### ISSUE TITLE
Show commands in [/] Menu in Telegram

### ISSUE THREAD

**Issue by cmantsch** [fabianonline/OctoPrint-Telegram#103]
The available commands should be shown in the Command Menu (Slash- Button on the right side next to the emoji Button)
It is really a hassle to input those commands manually especially on iOS, because autocorrect always changes /shutup to /Shutup, which is not recognised.
Telegram has that handy function for bot commands and it would make this plugin so much better :)

**Comment by derpicknicker1** [comment]
https://github.com/fabianonline/OctoPrint-Telegram#create-telegram-bot
See No. 5
