### ISSUE TITLE
Adding costs from CostEstimation

### ISSUE THREAD

**Issue by Fixel2012** [fabianonline/OctoPrint-Telegram#107]
Hi,

thank you for the great Plugin. 

I'd like to get the costs which get displayed by the CostEstimation Plugin in to my Telegram messages (Or just the last "print finished" message.

Is this somehow possible?

Would be great!

Thank you in advance.

**Comment by rlogiacco** [comment]
We have implemented the CostEstimation plugin integration in the next release
