### ISSUE TITLE
Command to send IP-Adress

### ISSUE THREAD

**Issue by basti30** [fabianonline/OctoPrint-Telegram#116]
A short command that returns the local ip adress. I know, setting a static ip might be easier. But sometimes it could be usefull.

Thank you for this amazing piece of software, I'm using it every day.

**Comment by guysoft** [comment]
Found https://github.com/fabianonline/OctoPrint-Telegram/wiki/Add-commands-and-notifications

And https://github.com/fabianonline/OctoPrint-Telegram/blob/master/octoprint_telegram/telegramCommands.py
Guess its to extend TCMD

**Comment by rlogiacco** [comment]
Next release will have the IP address reported in the `/sys` command reply: I didn't believe an entire new command would be needed just for a little info
