### ISSUE TITLE
socks5 proxy

### ISSUE THREAD

**Issue by clihlt** [fabianonline/OctoPrint-Telegram#126]
Telegram is blocked by censorship throughout Russia. Accordingly, the bots also can not work. Please add in the settings of the bot the ability to use the  socks5 proxy.

**Comment by NickRimmer** [comment]
I join you in the request,

**Comment by kiryam** [comment]
plus one for that

**Comment by Zoolu74** [comment]
I join! This function is needed as oxygen!

**Comment by ekorolkov** [comment]
+1

**Comment by diversunt** [comment]
+1 Very need!

**Comment by bumbalu** [comment]
+1 for this request

**Comment by bumbalu** [comment]
This is what I get:
![pic2](https://user-images.githubusercontent.com/35267448/39408998-9fba6e2e-4be7-11e8-9de9-8ba31c64a1ec.png)

**Comment by DmitryBellka** [comment]
+1

**Comment by clihlt** [comment]
Пацаны, зырьте на пулл реквест 128 идем туда и лайкаем. Он уже вовсю работает. Надо только вручную файлы подменить и прописать в конфиге прокси вручную.

**Comment by nizongdai** [comment]
+1 I need that too.

**Comment by filimonic** [comment]
+1

**Comment by dj140** [comment]
+1

**Comment by khode-mohsen** [comment]
i use this way , you just need install tor and run bot with

```bash
torify python3 bot.py
```

**Comment by hallskelet** [comment]
> 
> 
> Пацаны, зырьте на пулл реквест 128 идем туда и лайкаем. Он уже вовсю работает. Надо только вручную файлы подменить и прописать в конфиге прокси вручную.

Там полплагина пришлось руками пофиксить! и я боюсь его сейчас обновлять. хз добавил ли автор в релиз этот функционал или нет.

**Comment by idtools** [comment]
+1

**Comment by rlogiacco** [comment]
If you guys believe what you have wrote in Cyrillic might be relevant please translate for us :smile:

**Comment by clihlt** [comment]
Well 
1st cyr comment:
Guys, look at the pull request 128 we go there and like it. He is already working hard. It is only necessary to manually replace the files and register them in the proxy config manually.

Ans:
There I had to fix a half plugin with my hands! And I'm afraid to update it now. I don’t know if the author added this functionality to the release or not.

**Comment by Vasiy** [comment]
+1

**Comment by TechLifeTravel** [comment]
+1

**Comment by rubyfox** [comment]
+1
