### ISSUE TITLE
There isn't OctoPrint-Telegram in Plugin Manager

### ISSUE THREAD

**Issue by LolloMazzy** [fabianonline/OctoPrint-Telegram#130]
Why in octoprint say "Plugin installed successfully", but in terminal there are this error and in Plugin Manager there isn't Octoprint-Telegram???

![schermata 2018-05-04 alle 11 28 05](https://user-images.githubusercontent.com/10534882/39623197-1f4ff8c4-4f95-11e8-917e-ef7b7676f03a.png)
![schermata 2018-05-04 alle 11 32 32](https://user-images.githubusercontent.com/10534882/39623196-1f1d40dc-4f95-11e8-8296-37930fba30a6.png)

It's maybe because I have the version 1.3.8 of Octoprint?

**Comment by rlogiacco** [comment]
I hope you have this fixed by now 😄 
If I'm wrong, please reopen this issue.
