### ISSUE TITLE
Encoding error after /user

### ISSUE THREAD

**Issue by scmanjarrez** [fabianonline/OctoPrint-Telegram#144]
If you have unicode characters in your name the app won't send you the user information from the command /user.
Example: 
![imagen](https://user-images.githubusercontent.com/9284124/43498499-8550c854-9547-11e8-8ffa-7a2b8aa093a8.png)
First Name -> 𝐻𝑒𝓁𝓁𝑜 𝓌𝑜𝓇𝓁𝒹, 𝓉𝒽𝒾𝓈 𝒾𝓈 𝒶 𝓉𝑒𝓈𝓉!
Log file: 

> 2018-07-29 19:48:30,412 - octoprint.plugins.telegram.listener - INFO - Got a command: '/user' with parameter: '' in chat xxxxxxxxx
> 2018-07-29 19:48:30,416 - octoprint.plugins.telegram.listener - ERROR - Exception caught! 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
> 

I have created a PR #145 in order to fix this error.

**Comment by rlogiacco** [comment]
Should get fixed in the next release
