### ISSUE TITLE
[feature] cam-picture

### ISSUE THREAD

**Issue by MicrowaveX** [fabianonline/OctoPrint-Telegram#15]
Hi,

i'm quite excited about your plugin! Great work!
I experimented with your plugin-code and added a feature (/campic) which just sends a picture of the printer's cam regardless of the current printing state.

Not sure if you wanna implement it:

`elif command==gettext("/campic"):
    self.main.track_action("command/campic")
    self.main._send_msg("Ok, here we go you little stalker...", with_image=True)
`

**Comment by fabianonline** [comment]
Hi.
Thanks a lot for your support. But did you have a look at the `/status` command? That does essentially the same, just with a little bit more status information... ;-)

**Comment by MicrowaveX** [comment]
Yes, but it doesn't send you a pic when you're not connected to the printer ^^

**Comment by fabianonline** [comment]
Okay, I don't know why I did it that way, but it seems kinda silly to me now. I'll just change that so you won't need to have another command.

**Comment by MicrowaveX** [comment]
Ah ok cool! Great :)

**Comment by fabianonline** [comment]
This feature is included in version 1.2.0 which I've just pushed to github.
