### ISSUE TITLE
Layernumbers

### ISSUE THREAD

**Issue by Bishamon1987** [fabianonline/OctoPrint-Telegram#150]
Can someone add layernumbers as variable? 
So you can get messages like   `Printing layer 32 / 200 (16%)`

**Comment by rlogiacco** [comment]
This is not as easy as it might seem: octoprint doesn't currently have such information unless the whole gcode is parsed, which is a non trivial operation and quite intensive.

**Comment by giloser** [comment]
possible in #338 with DiplayLayerProgress
