### ISSUE TITLE
doesn't work with octoprint 1.3.9

### ISSUE THREAD

**Issue by getharder** [fabianonline/OctoPrint-Telegram#151]
after upgrading to octoprint 1.3.9, plugin stops sending to telegram. setup works, e.g. testing the bot but there is no start/end picture, nor does the printer react to commands send per telegram.

**Comment by FranzSw** [comment]
And - I don't know if it is the same for you - it is not visible in the menu after installation.

**Comment by Rotzbua** [comment]
Plugin works for me with octoprint 1.3.9.

**Comment by getharder** [comment]
Great!

**Comment by Rotzbua** [comment]
> Great!

I know!

**Comment by getharder** [comment]
fixed.
