### ISSUE TITLE
Chrome crash everytime when I load a g-code over 40M

### ISSUE THREAD

**Issue by nizongdai** [fabianonline/OctoPrint-Telegram#154]
everytime if I try to load a G-code file over 40M, it can print, but if I open the G-code viewer, after the loading to 100%, Chrome just crashed. and I need refresh the page. how can I fix this, I have 16G RAM on my computer.

**Comment by fabianonline** [comment]
This sounds like a problem caused by Octoprint itself. This is the repository for the octoprint-telegram plugin. Since your question doesn't seem to be related to Telegram, I'll close this issue. Feel free to comment on it or reopen it if I'm mistaken.
