### ISSUE TITLE
When downloading a file, the WEB GUI is reloaded

### ISSUE THREAD

**Issue by EddyMI3d** [fabianonline/OctoPrint-Telegram#155]
Hi!
With the plugin installed, every time when a file is downloaded from OctoPrint, the WEB GUI is restarted/reloaded.
![op_tn_s](https://user-images.githubusercontent.com/8533327/49878702-83e88200-fe28-11e8-84e8-8e80364168c2.jpg)
I'm using Raspberry Pi 3 B
OctoPi 0.15.1
OctoPrint 1.3.10 (the issue already appeared with 1.3.9)

**Comment by rlogiacco** [comment]
This should be fixed with next release: please re-open if you are still experiencing this issue after upgrading
