### ISSUE TITLE
Are the DEVS Quit?

### ISSUE THREAD

**Issue by ygtc** [fabianonline/OctoPrint-Telegram#158]
no update from 2017 until now.
I like to use this plugin and still i am using but plugin had issues and nobody resolve these.

Are the developers quit this plugin?

**Comment by MoshiBin** [comment]
@fabianonline can you confirm if this project is abandoned? Can you pass the mantle to someone else?

@ygtc do you know if there's an active fork of this project?

**Comment by MarcusWolschon** [comment]
ygtc: could you please change the tile to something that resembles English grammar? Thank you.

**Comment by ygtc** [comment]
@MoshiBin i don't know but you can try octoprint-ifttt plugin. Only difference is you have to use webhooks every single operation but pretty usefull.

@MarcusWolschon i think message is clear for understanding.Thank you for suggestion.

**Comment by MoshiBin** [comment]
@MarcusWolschon title*. Try to be tolerant of people who aren't native speakers. In your comment, providing an alternative title would be far more beneficial and less hostile than blandly criticizing the OP.

**Comment by MarcusWolschon** [comment]
Thank you for mistaking me for a native english speaker.

**Comment by fabianonline** [comment]
Hi.

Well, at least one of the Devs didn't quit, I just didn't have time to spare for this project. But today I started working on the code again. More maintaining and bug fixing then adding new features, but working on it nonetheless.

I'll close this ticket since the question is answered now. ;-)
