### ISSUE TITLE
Telegram plugin disappeared from octoprint 

### ISSUE THREAD

**Issue by SimoneBnc** [fabianonline/OctoPrint-Telegram#166]
After an OS update I lost the telegram plugin. I tried to Uninstall it and install it several times (installation is successful every time) but it is no longer showing in octoprint and of course it is no longer working. I even tried to update octoprint to the RC11 but still no luck. Is there a way to figure out what happened?

**Comment by rlogiacco** [comment]
We need to have a look at your `octoprint.log`

**Comment by SimoneBnc** [comment]
Do you want it after I uninstall and reinstall the plug in or just the file after the startup?

**Comment by rlogiacco** [comment]
I believe the version you tried to install is the last stable ('1.4.2') so the startup should be fine, just ensure you have the [debug logging enabled](https://github.com/fabianonline/OctoPrint-Telegram/wiki#how-do-i-enable-debug-logging) before restarting.

**Comment by SimoneBnc** [comment]
I tried to install it but it does not show in the plugin page and every time I search for new plugins it always shows the INSTALL button, it successfully installs the plugin but it still missing from octorpint.

**Comment by SimoneBnc** [comment]
nevermind... I made a fresh install.
