### ISSUE TITLE
Bot is flipping out

### ISSUE THREAD

**Issue by ulope** [fabianonline/OctoPrint-Telegram#171]
Since yesterday my telegram bot has totally lost it:

![ezgif-1-8824dab3ef04](https://user-images.githubusercontent.com/55078/56911604-94368c00-6aad-11e9-947f-cafe93132468.gif)

If there are any logs I should provide, please tell me.

**Comment by Pimentoso** [comment]
Same issue here, following.

**Comment by ulope** [comment]
I “solved” the issue by deleting and re-creating the bot in telegram.

**Comment by rlogiacco** [comment]
Please reopen if this happens again: we are more than willing to investigate, but we need additional details which are very probably not available anymore in your logs.
