### ISSUE TITLE
After Octoprint upgrade to 1.3.11 telegram plugin is unable to format emo:rocket and other emos

### ISSUE THREAD

**Issue by bumbalu** [fabianonline/OctoPrint-Telegram#174]
Hello, everyone. 
After Octoprint upgrade to 1.3.11 telegram plugin send the following message after octoprint start: 
===
ERROR: I was not able to forman the Notification for 'PrinterStart' properly. Please open your Octoprint settings for Telegram Notifications and check message settings for 'PrinterStart'
===
I have tried to switch on/off the markup selection or html - it did not help. Then I removed the brackets on both ends of {emo:rocket} and telegram plugin successfully formats notifications. 

We obviously can happily live without those nice emoticons but getting them back would be pleasant.  
Anybody has any ideas?

**Comment by xenon2008** [comment]
I also have the same Error!

See Also my Post @Octoprint Github Post here:
https://github.com/foosel/OctoPrint/issues/3150

**Comment by TheLion** [comment]
Same issue also.

**Comment by VanKurt** [comment]
metoo ;-)

**Comment by Evg33** [comment]
#93

**Comment by pokono** [comment]
+1

**Comment by Piranit** [comment]
Just delete all emo from messages.
![image](https://user-images.githubusercontent.com/8013207/58044232-ed8f5980-7b47-11e9-8981-93916b0d177f.png)

**Comment by avrahams** [comment]
same issue since upgrade to 1.3.11 - worked fine before the upgrade

⚠ ERROR: I was not able to format the Notification for 'PrinterStart' properly. Please open your OctoPrint settings for Telegram Notifications and check message settings for 'PrinterStart'.

All messages are with defult format 
PrintDone: Finished printing {file}.

**Comment by Brain-Gamer** [comment]
It seems to work without any kind of issue if you use 2 spaces after the last emo instead of just one.
So instead of `{emo:rocket} Hello....` you use `{emo:rocket}  Hello....`
No idea why but this workaround fixed the issue for me.

**Comment by friedl** [comment]
> 
> 
> It seems to work without any kind of issue if you use 2 spaces after the last emo instead of just one.
> So instead of `{emo:rocket}[SPACE]Hello....` you use `{emo:rocket}[SPACE][SPACE]Hello....`
> No idea why but this workaround fixed the issue for me.

Just tried this and it worked.

**Comment by sagatxxx** [comment]
Same here, solved with Two spaces

**Comment by Budavaril** [comment]
Found that actually "no space" or "two spaces"..

**Comment by careyer** [comment]
Same here... problem still persists... workaround with TWO SPACES works
