### ISSUE TITLE
Weird user connected to plugin

### ISSUE THREAD

**Issue by ThaliaFromPrussia** [fabianonline/OctoPrint-Telegram#176]
I got a weird user in my plugin. Is this the Telegram bot? Can't find any information in the readme. So I did not give him any rights. As I search for the ID or name Telegram doesn't know the user.
Thanks in advance!

![2019-05-22 16_55_01-Window](https://user-images.githubusercontent.com/28732158/58185094-ab365b80-7cb2-11e9-9e16-41a88dd78799.jpg)

**Comment by Ozkovacs** [comment]
I have the same situation, with a user called "Mekan - Bilmez / ID: 727602521 | PRIVATE".
Whenever I remove it, it gets added back automatically.
I know that I re-installed Octoprint at some point, and had to re-enable the plugin.  Can that be a reference to my older setup?!?  I doubt it, but I think it's worth mentionning.

**Comment by rlogiacco** [comment]
The bots are open for public access: those are people bumping into your bots either by mistake or attempting to hack. Just be sure to refrain giving those users any permission and you will be good to go.
