### ISSUE TITLE
Please add a notification for user interaction requests

### ISSUE THREAD

**Issue by brickkk** [fabianonline/OctoPrint-Telegram#181]
Please add a notification if user interaction on the printer is necessary
(Maybe use PauseForUser Event Plugin: https://plugins.octoprint.org/plugins/PauseForUserEvent/ )

**Comment by TheLion** [comment]
+1

**Comment by mrjackson** [comment]
This would be great for people with the Prusa MMU or anyone adding manual filament changes.

**Comment by rlogiacco** [comment]
Would you guys be willing to develop this and submit a pull request? You know, this is open source software and lives of contributions

**Comment by ZeGuigui** [comment]
> Would you guys be willing to develop this and submit a pull request? You know, this is open source software and lives of contributions

I have some working code, now I have to learn how to create pull requests 🤣

**Comment by kanocz** [comment]
@ZeGuigui just create fork, put changes, commit, then click "pull request" :)

**Comment by ZeGuigui** [comment]
> @ZeGuigui just create fork, put changes, commit, then click "pull request" :)

Done! Learned how to create and apply patches at the same time
