### ISSUE TITLE
Automatically start printing file  when uploaded via telegram

### ISSUE THREAD

**Issue by mindlux** [fabianonline/OctoPrint-Telegram#183]
Even just had this at a simple option to enable to allow for immediate printing

**Comment by rlogiacco** [comment]
If my understanding is correct, if we decide to implement this feature what we will achieve is reducing a _two-click_ operation down to a _one-click_ operation... 
I believe we can leave without it unless I am missing something...

**Comment by derpicknicker1** [comment]
I think this should not be integrated for safety reasons. We won't start a print without confirming it.
Also it will not be possible to upload multiple files when printing starts automatically with each file.

**Comment by rlogiacco** [comment]
totally agree
