### ISSUE TITLE
"Delete user" not working as intended?

### ISSUE THREAD

**Issue by naikio** [fabianonline/OctoPrint-Telegram#190]
When i click the "TrashBin" icon under Known Chats, the user is deleted from the list but he's still able to send and receive messages (and in fact, if i click "Reload" the user shows up again in the list of Known Chats)

I'm attaching the logs after activating the "DEBUG level" option. 

**Not related to this, but still relevant: i just saw that the DEBUG log is actually logging my bot's token. Is this safe?** 
[octoprint.log](https://github.com/fabianonline/OctoPrint-Telegram/files/3465294/octoprint.log)

**Comment by derpicknicker1** [comment]
After clicking the trash bin, you have to click on the save button of the settings dialog.

Regarding the token: it is save as long as you don't share the token. If you will do so by accident, you can generate a new token for your bot, so you are save again. (https://core.telegram.org/bots#generating-an-authorization-token)
