### ISSUE TITLE
Filamentmanager - Error

### ISSUE THREAD

**Issue by Haschtl** [fabianonline/OctoPrint-Telegram#195]
The filament Manager seems to only work, if Octoprint runs AT Port 80. Mine runs AT Port 5000. I'm Sure i have installed the filament Manager plugin

Response:
😖 Error changing spool
Error text: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /plugin/filamentmanager/spools was not found on this server.</p>
<hr>
<address>Apache/2.4.38 (Raspbian) Server at localhost Port 80</address>
</body></html>

**Comment by rlogiacco** [comment]
That should be investigated and fixed if confirmed: thanks for reporting the issue
