### ISSUE TITLE
After using /gif once it automatically sends gifs after every status update.

### ISSUE THREAD

**Issue by cepxuo** [fabianonline/OctoPrint-Telegram#196]
Hi! New gif function is awesome, but how to make the bot to send gifs only when it is asked for?
I tried it once, but after that the bot started sending me gifs with every status update. Rendering gifs is pretty hard for raspberry pi with FullHD cam, so it affects certain layers quality.

Is there a way to receive gifs only upon command?

**Comment by giloser** [comment]
Hi,
so it's not checked in the plugin configuration? And yet after one call of the command /gif it start to send it every time with the status?

**Comment by cepxuo** [comment]
Oops! I am sorry! The option was enabled in config. I did not noticed it.
