### ISSUE TITLE
Run system commands

### ISSUE THREAD

**Issue by fabianonline** [fabianonline/OctoPrint-Telegram#21]
Any way to send system commands?  IE w the systems command editor I now have a power on/off menu item.  This triggers a gpio command to turn on a relay and power the printer.

**Comment by derpicknicker1** [comment]
Will custom gCode-commands solve the problem? Like M80 / M81?
Directly sending system commands is a security issue, i think. 
Maybe the known commands from system command editor can be dinamically included to the telegram plugin. Should be possible.

**Comment by derpicknicker1** [comment]
Comming soon:
https://github.com/derpicknicker1/OctoPrint-Telegram/commit/eb4808a7efb8fe9ce0eebdd9ac6e8b566d9fe570

**Comment by derpicknicker1** [comment]
Feature released in 1.3.0 
https://github.com/fabianonline/OctoPrint-Telegram/releases/tag/1.3.0
