### ISSUE TITLE
Change the timezone

### ISSUE THREAD

**Issue by Kawuezel** [fabianonline/OctoPrint-Telegram#211]
Hi,

I have the issue that in Telegram, the plugin is sending me the false ETA time. It's 2 hours behind my timezone in central europe. On the Octoprint dashboard, it's showing for example 15h18, but in the message in telegram, it shows 13h18.

Is there a way to change the timezone, or is there another problem?

Thanks,
Kim

**Comment by giloser** [comment]
Hi ,

have you check/configure the timezone of your PC/raspberry
on a raspberry it could be done with the raspiconfig.

Gilles

**Comment by MarcusWolschon** [comment]
Given that Octoprint uses the same timezone, this seems unlikely.

**Comment by w4-sglim** [comment]
I just changed the timezone in Raspberry pi so I'm sure that octoprint-telegram uses the same timezone with octoprint and raspberry itself.

**Comment by Kampfqualle** [comment]
I have the same issue.
Time in OctoPrint is correct, but Telegram is 1h behind.

**Comment by melvinisken** [comment]
Same for me. Telegram is 1h behind.

**Comment by ftzhurrey** [comment]
Yeah, got the same problem. 1h behind.

**Comment by developnoop** [comment]
Same Problem here, central europe. 
Do you need any kind of log file or other info?
The ETA you see in the GUI of Octoprint is correct, but the Telegram ETA is 1h behind.

**Comment by SM-26** [comment]
Still got the problem.
If someone found a workaround, please let us know

**Comment by texttoolong** [comment]
Please SSH into your octopi.local.
Type "date" - you will probably get returned the wrong time (unset = set to London time). 
Type "sudo dpkg-reconfigure tzdata" and select your time zone. 
Done.
All the best, Thomas

**Comment by developnoop** [comment]
> 
> 
> Please SSH into your octopi.local.
> Type "date" - you will probably get returned the wrong time (unset = set to London time).
> Type "sudo dpkg-reconfigure tzdata" and select your time zone.
> Done.
> All the best, Thomas

You are 100 % correct. This solved the issue!
Maybe someone should add this to the wiki here?
@texttoolong Thank you for this insight!

**Comment by LeightonSolo** [comment]
I'm using Octo4a on an android phone as my Octoprint installation. The phone timezone is correct but it isn't in Octoprint, any idea how to change for Android instead of raspberry pi?
