### ISSUE TITLE
Gif not loading in Telegram app....

### ISSUE THREAD

**Issue by mygitcrazy** [fabianonline/OctoPrint-Telegram#218]
Everything is working as expected and i really like it. Only problem is that the gif (cam snapshot) that's being send is showing up, but stays blurry with a spinning wheel in the middle... :-((

What could be the problem? I've tried different settings in the snapshot url settings and played around with the notification settings but no luck

**Comment by mygitcrazy** [comment]
![Uploading Screenshot_20191111-223803_Telegram.jpg…]()

**Comment by mygitcrazy** [comment]
![Screenshot_20191111-223803_Telegram](https://user-images.githubusercontent.com/30736903/68623203-3f4fe580-04d4-11ea-92a1-a4c695a161fb.jpg)

**Comment by giloser** [comment]
Hi there,

it's seems that the screen shot from connection has the same problem so It's probably not a GIF issue.
Are you in Wifi or in data connection on your device with telegram?
how are your settings in the Data and storage?
does the Telegram app has the right to save local data on your device?

thanks
Gilles

**Comment by mygitcrazy** [comment]
Thanks for the good advice ;-)) 

I checked the app settings, Data and Storage, that one was checked and active. That wasn't the problem. The problem is in the Wifi and data connection. As soon as I switched over from Wifi to Mobile Data connection the snapshots (gifs) came through. But one question left... why is it only available through Mobile Data connection? .......

**Comment by mygitcrazy** [comment]
Ps

I shall close this issue as soon as possible.. cause it solved my problem till so far and I'm happy it works now :)

**Comment by mygitcrazy** [comment]
One question left... why is it only available through Mobile Data connection? .......

**Comment by giloser** [comment]
well it's working fine for me on wifi or mobile data.

Could you show a print screen of your telegram settings for that part?

thanks

**Comment by mygitcrazy** [comment]
That's weird for my case then. Could it be a firewall related thing maybe? My network is in a heavily protected environment. What kind of settings of  Telegram do you need by the way? I see a lot of settings over there....

Thanks for your help by the way :-))
