### ISSUE TITLE
Request: Message on waiting for filament change (M600)

### ISSUE THREAD

**Issue by PetrGasparik** [fabianonline/OctoPrint-Telegram#227]
Prusa printers has a command M600 for filament change. It makes printer wait for user to change filament. 

This is basically used for color print. 

Please support this. See https://blog.prusaprinters.org/color-print/ for info.

**Comment by MarcusWolschon** [comment]
This sounds useful.

**Comment by Prizmagnetic** [comment]
I have M600 trigger a pause in Octoprint, because I dont have a screen attached to the printer and I need to change the filament in the octoprint filament manager anyway. I haven't tried this but, I think you would get a message when octoprint pauses that way

**Comment by giloser** [comment]
duplicate with #213
