### ISSUE TITLE
Notification on Color Change

### ISSUE THREAD

**Issue by Harald777** [fabianonline/OctoPrint-Telegram#229]
I am using this great plugin for a while now, really a good addition for my Prusa i3 MK3s usage.
Lately i am into multicolour printing (no MMU) and it would be great if the plug-in could detect the colour change moment and send a notification.
Hope to see such function in the near future.

Greetings,

Harald

**Comment by ZeGuigui** [comment]
I did a pull request to support this feature! You will also need the PauseForUser Event Plugin. See pull request #204 and issue #181 !

**Comment by klsc18** [comment]
I'm also waiting for it, that would help a lot

**Comment by giloser** [comment]
# # #338
