### ISSUE TITLE
PSU control feature.

### ISSUE THREAD

**Issue by xoniq** [fabianonline/OctoPrint-Telegram#231]
I’m using the PSU control plugin to turn printer on and off, would be handy to see this in Telegram.

**Comment by wtrevine** [comment]
Yea. I need that too! I cannot connect my printer via telegram!

**Comment by MarcusWolschon** [comment]
Is there some kind of commands-api for actions provided by 3rd party plugins that we can bind the Telegram plugin to?
Instead of people requesting custom code for their special plugin XYZ to be added (and then maintained for years) to the Telegram plugin.

**Comment by samuelmscott** [comment]
PSU Control has an API which uses Curl commands: https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/API

**Comment by giloser** [comment]
check V1.6.3
