### ISSUE TITLE
Cannot load filelist when installed OctoPrint-UltimakerFormatPackage

### ISSUE THREAD

**Issue by alexandrkut** [fabianonline/OctoPrint-Telegram#237]
Hello.
After installing plugin "OctoPrint-UltimakerFormatPackage" Telegram bot can not load file list after command /print or /files.
"Loading files..." and stuck

Link on plugin: https://plugins.octoprint.org/plugins/UltimakerFormatPackage/

**Comment by MarcusWolschon** [comment]
Can you provide a log file and/or stack trace?

**Comment by derpicknicker1** [comment]
Will be fixed in next release. Working on this. same as #236
