### ISSUE TITLE
Automatic update fails

### ISSUE THREAD

**Issue by BerndJM** [fabianonline/OctoPrint-Telegram#24]
The update via octoprint - Version: 1.3.0.dev1047+g5a5d29b (devel branch) - fails.
Here the relevant part from the logfile:

> 2016-05-19 22:59:07,686 - octoprint.plugins.softwareupdate - INFO - Starting update of telegram to 1.3.0...
> 2016-05-19 22:59:07,706 - octoprint.plugins.softwareupdate - ERROR - Update of telegram can not be performed
> Traceback (most recent call last):
> File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.dev1047_g5a5d29b-py2.7.egg/octoprint/plugins/softwareupdate/__init__.py", line 666, in _perform_update
>     update_result = updater.perform_update(target, populated_check, target_version, log_cb=self._log)
>   File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.dev1047_g5a5d29b-py2.7.egg/octoprint/plugins/softwareupdate/updaters/pip.py", line 66, in perform_update
>     install_arg = check["pip"].format(target_version=target_version)
> KeyError: 'target'

**Comment by derpicknicker1** [comment]
Please see closed Issue #23 . We are sorry about that.
