### ISSUE TITLE
Incompatible Python 3.6

### ISSUE THREAD

**Issue by gvmturl** [fabianonline/OctoPrint-Telegram#244]
Could you please update it?

Thank you for the job!

**Comment by gvmturl** [comment]
Cant use the plugin with python 3.7 any solution please:

**Comment by rlogiacco** [comment]
The author and his apprentices are working on this, you might want to find a way to support his efforts and show your appreciation for his donation to the community ;-)

**Comment by gvmturl** [comment]
Tried adding __plugin_pythoncompat__ = ">=2.7,<4" on __init__.py of python3 branch. could make it work but the listener is not working... 
ERROR: I was not able to format the Notification for 'PrinterStart' properly. Please open your OctoPrint settings for Telegram Notifications and check message settings for 'PrinterStart'.

And 

I do not understand you! 

Are the messages that i m receiving from bot... any help?

Thank you guys!

**Comment by gvmturl** [comment]
Is there any news about the python 3 compatibility?

**Comment by szobov** [comment]
Hi there,
I've fixed **python3** incompatibility in my fork: https://github.com/szobov/OctoPrint-Telegram
But I didn't prepared it for this repo, because I didn't spend time to fix it for **python2**.
You're welcome to check:
```
python -m pip install "https://github.com/szobov/OctoPrint-Telegram/archive/master.zip"
```
Cheers.

**Comment by MarcusWolschon** [comment]
Can you create a pull request?

**Comment by szobov** [comment]
> Can you create a pull request?

Sure, here it is:
https://github.com/fabianonline/OctoPrint-Telegram/pull/273

**Comment by xbarents** [comment]
Octoprint made a anncouncement for a conversion script to migratie from python 2 to 3. We can expect more questions coming because Telegram will not work anymore after running the script.

Is there any timeframe when the plugin will be updated?

**Comment by maier-johno** [comment]
Hello, i have tested it too. First, the upgrade was without errors. But my telegram-plugin don't work. And my FilamentManager-Plugin can't connect to my database on a other RasPi. So, i go back with your " https://raw.githubusercontent.com/cp2004/Octoprint-Upgrade-To-Py3/master/go_back.py" script. This works great too!

That's the only reason why i go back. But respect, both scripts works perfectly! Octoprint with Python 3.6 too!

Great job and thank's for the great scripts!

**Comment by fractalsauce** [comment]
@Thanks for the fix @szobov :)

**Comment by FranciscodeMaussion** [comment]
This is mandatory, for now we can use [szobov solution](https://github.com/fabianonline/OctoPrint-Telegram/issues/244#issuecomment-659382633). Thanks @szobov
