### ISSUE TITLE
Multicam + Telegram

### ISSUE THREAD

**Issue by petitxef** [fabianonline/OctoPrint-Telegram#251]
Hi!

It's not a issue, just wondering how and if it's possilbe to configure Telegram to get integration with Multicam imput.

Right now just Telegram get the picture of the "First" pluged webcam. It's possible to get the option to picture (or GIF) from the second webcam?

Thanks!

**Comment by petitxef** [comment]
Close please, I found similar topic here:
https://github.com/fabianonline/OctoPrint-Telegram/issues/214

**Comment by rlogiacco** [comment]
Are you willing to help us test the correct support for multiple cameras? If you are please leave a message in the Telegram Plugin Users group
