### ISSUE TITLE
Webcam Rotated

### ISSUE THREAD

**Issue by alnavasa** [fabianonline/OctoPrint-Telegram#253]
I know there is a issue for this but was closed without a fix,

I am receiving images upside down on my telegram while I get to see them properly on the octopi.local site, and porperly on the cura monitor page.

Cura:
<img width="1284" alt="Cura" src="https://user-images.githubusercontent.com/458370/79201722-c8c76300-7e38-11ea-9996-6bb5b67a5629.png">

Octopi:
<img width="1165" alt="Octopi" src="https://user-images.githubusercontent.com/458370/79201727-c9f89000-7e38-11ea-9a05-67d0d65a8286.png">

Telgram:
<img width="327" alt="Telegram" src="https://user-images.githubusercontent.com/458370/79201728-ca912680-7e38-11ea-9c38-da7cb3ff4f3f.png">

**Comment by f4nu** [comment]
Hey @alnavasa did this PR fix your issue?
