### ISSUE TITLE
Enhancement: Wait for end script to complete before sending notification

### ISSUE THREAD

**Issue by KevinNovak** [fabianonline/OctoPrint-Telegram#254]
It would be handy to delay the notification until the end script in OctoPrint has completed.

For example, I would like to wait for the bed to completely cool before receiving the notification:
![Example](https://i.imgur.com/zIC3jT8.png)

I know there is a delay option which is also handy but in my scenario the cooldown does not always take the same amount of time.

Regardless thank you for your work on this plugin, it's been incredibly helpful to me since my printer is multiple floors below me.

**Comment by iaglet** [comment]
it might be the same thing but telegram is notifying me WAY before the print is complete that the print is complete.

**Comment by sungo** [comment]
@iaglet I just filed a separate ticket for that behavior. I'm seeing the same thing. https://github.com/fabianonline/OctoPrint-Telegram/issues/262
