### ISSUE TITLE
Error sending gcode file

### ISSUE THREAD

**Issue by mwhuss** [fabianonline/OctoPrint-Telegram#26]
With 1.3.1 and when trying to send a gcode file.

2016-05-22 22:29:54,880 - octoprint.plugins.telegram.listener - ERROR - Exception caught! local variable 'data' referenced before assignment

**Comment by derpicknicker1** [comment]
Thanks for leaving a note on this. It's fixed in this d09800a5cb985c413ba0a10bf71210ca2645b30f commit and will be included in the next update, which is comming soon.

**Comment by derpicknicker1** [comment]
Fixed in https://github.com/fabianonline/OctoPrint-Telegram/releases/tag/1.3.2
