### ISSUE TITLE
Sending notifications on "Print Finishing" not "done"

### ISSUE THREAD

**Issue by sungo** [fabianonline/OctoPrint-Telegram#262]
Near as I can tell, I'm getting "Print Complete" notifications based on Octoprint's "Print Finishing" state, not completion. "Print Finishing" occurs when Octoprint has finished reading the gcode file, not when the print is complete. On my Prusa MK3S, the time between "done reading the file" and "done sending the gcode to the printer" is a couple of minutes. Would it be possible to change the trigger?

**Comment by iaglet** [comment]
i believe this is related to #254

**Comment by giloser** [comment]
there is now a delay for the Print finishing message so I'll close this one
