### ISSUE TITLE
Message at PrintPaused

### ISSUE THREAD

**Issue by The-Holgi** [fabianonline/OctoPrint-Telegram#264]
Hello,
i´m using Octoprint with Klipper.
The Telegram plugin sends all messages but not at print paused.

**Comment by Deses** [comment]
Mine does. 🤔

Give more info: Plugin version, Octorprint version, Python 2 or 3? Did you double check the option is enabled?
Is Klipper using the same pause/resume gcode as Marlin?

**Comment by giloser** [comment]
this problem will be close as the author never answer to get more info
