### ISSUE TITLE
User "@toppper" keeps adding himself to user list

### ISSUE THREAD

**Issue by Klammerson** [fabianonline/OctoPrint-Telegram#265]
I have an unknown user

<img width="647" alt="Screenshot 2020-06-05 um 11 04 32" src="https://user-images.githubusercontent.com/65161811/83858237-74e04880-a71c-11ea-8105-e3dcdf4eb83e.png">

He keeps adding himself to the list. I remove him every time but he keeps coming back.

I'm trying to restrict access but I can't find where.

**Comment by fabianonline** [comment]
That table just lists all known users. A user is known to the bot once they interacted with the bot. After a reload of the plugin, that list gets populated again, so he keeps reappearing.
As long as you don't allow him to perform any actions or enable notifications for him, he won't be able to use your bot in any way.
