### ISSUE TITLE
{time_finish} / ETA variable not working

### ISSUE THREAD

**Issue by Quintin9801** [fabianonline/OctoPrint-Telegram#272]
Octoprint version: 1.4.0 Win10
Telegram Plugin version: 1.5.0
Telegram App Version: 6.2.1

When receiving zchange notifications, My {time_finish} variable does not show anything, even when close to the end of a print (after it as time to calculate ETA). Are there any fixes for this issue that I am missing? Is eta calculated from an external plugin?

![image](https://user-images.githubusercontent.com/35208750/87667166-7e070100-c72f-11ea-99b8-28b60111022a.png)
![chrome_bS89pSsBiL](https://user-images.githubusercontent.com/35208750/87667222-98d97580-c72f-11ea-9065-3795a50b5cd2.png)

ZChange Script:
```
{emo:<info>} Printing, *{percent}% done* 
*Extruder* {e1_temp}/{e1_target}.
Time Done: {time_done}
Time Left: {time_left}
Time Finish: {time_finish}

[OctoPrint](192.168.1.60:5000)
[OctoAnywhere](https://www.getanywhere.io/app/devices#)

/status
```

**Comment by giloser** [comment]
hi is this still a problem?

**Comment by Quintin9801** [comment]
@giloser No this is not a problem anymore, this was patched in a previous update. I forgot this thread was still open.
