### ISSUE TITLE
Add option for custom notifications trigger by GCODE

### ISSUE THREAD

**Issue by tourbino** [fabianonline/OctoPrint-Telegram#274]
I'm looking for an opportunity to get notifications for M600, filament change on my mobile phone. I really like the telegram plugin, but can't seem to find a way around. I see many issues on this here.

If it's not desired to cater for such a specific need, what about adding the option for a custom event based on GCODE sent to the printer? Then those of us can set up a notification based on M600

**Comment by giloser** [comment]
duplicate with #213
