### ISSUE TITLE
Not installing through the plugin manager.

### ISSUE THREAD

**Issue by grossqx** [fabianonline/OctoPrint-Telegram#277]
Used this plugin before, but with the most recent update of Octoprint to 1.4.1 it just disappeared. Trying clearing date and reinstalling it. Process goes, but after reload it's not there. All the other plugins remained in place

**Comment by cp2004** [comment]
See the release notes for OctoPrint 1.4.1.

This has been fixed in the latest version of the plugin, 1.5.1. You may have to 'force check for updates' or manually reinstall.

I believe this is because the listing in the plugin repo is targeting the branch `stable`, which has not been updated.

@giloser Please either merge the branch `master` to `stable` or update the plugin repo listing, ASAP

**Comment by rogeliodh** [comment]
update fails with:

```
Updating, please wait.
/home/rogelio/OctoPrint/bin/python2 -m pip --disable-pip-version-check install https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip
ERROR: HTTP error 404 while getting https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip
ERROR: Could not install requirement https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip because of error 404 Client Error: Not Found for url: https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip
ERROR: Could not install requirement https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip for URL https://github.com/fabianonline/OctoPrint-Telegram/releases/1.5.1/download/release.zip
```

**Comment by tobyfu** [comment]
I managed to get it updated by doing an install by URL with this link https://github.com/fabianonline/OctoPrint-Telegram/archive/1.5.1.zip

**Comment by falsechicken** [comment]
> I managed to get it updated by doing an install by URL with this link https://github.com/fabianonline/OctoPrint-Telegram/archive/1.5.1.zip

Yep this works as a temporary workaround.

**Comment by grossqx** [comment]
I can confirm that it works.

**Comment by cp2004** [comment]
This issue should now be solved, as plugin repository has been updated.

 To @giloser or whoever is maintaining this plugin, **the plugin repo has been changed to target `master`, no longer `stable`** to work around this issue as it is very widespread, and causes issues for OctoPrint as tickets are opened there, complaining about this problem. 
If this needs changing please open an issue there.
