### ISSUE TITLE
Allow to select which notifications are to be sent

### ISSUE THREAD

**Issue by nicolinux** [fabianonline/OctoPrint-Telegram#29]
First, thanks for the fantastic plugin!

I'd like to be able to specify which messages to send. For example I don't need the "printer shutdown" or "printer started" notifications, but there is no way to disable them.

**Comment by derpicknicker1** [comment]
There is a way to disable them! When you klick the blue notification icon (speech bubble) for a user in the list, you can select which Notifications will be send to the user.

**Comment by MarcusWolschon** [comment]
This issue is still open. Can it be closed?

**Comment by nicolinux** [comment]
Yep, thanks.
