### ISSUE TITLE
Time and Height notification is not working

### ISSUE THREAD

**Issue by ViiFii** [fabianonline/OctoPrint-Telegram#290]
Hello.
Plugin installed and respond to /status etc commands.. but configured notifications to registered users are not working at all... Didn't find any solution so, post request here.
<img width="262" alt="Screenshot 2020-10-03 at 11 22 07" src="https://user-images.githubusercontent.com/68652774/94986836-ae11b380-056a-11eb-8169-f32e8310f23c.png">

**Comment by TobiasBales** [comment]
same for me

**Comment by techunreal** [comment]
same here

**Comment by chatainsim** [comment]
Same here too!

**Comment by ViiFii** [comment]
Solved

**Comment by TobiasBales** [comment]
@ViiFii so how was it solved? Would be good to know really because for me everything is up-to-date but it still does not work

**Comment by ViiFii** [comment]
> @ViiFii so how was it solved? Would be good to know really because for me everything is up-to-date but it still does not work

hi. just press "balloon" under "Notify" and set all you need ;-)
