### ISSUE TITLE
After upgrading - You are not allowed to do this! 😬

### ISSUE THREAD

**Issue by r0ndL** [fabianonline/OctoPrint-Telegram#30]
After I upgraded Telegram.  I'm receiving "You are not allowed to do this! 😬" alert whenever I try to send a command.  In octiprint the Chat user has the correct rights.

**Comment by daltonswayze** [comment]
Are you still having this issue? I have the same problem only I never had it working, just did a fresh install of octoprint 1.2.13 and follow the directions here https://github.com/fabianonline/OctoPrint-Telegram/blob/stable/README.md

**Comment by flow23** [comment]
Dito

**Comment by orangeudav** [comment]
+1

**Comment by Xoius** [comment]
Yes, this is a little bit anoying ^^

**Comment by orangeudav** [comment]
You must enable separate permissions _inside_ command and notify icons (click both on them) for the first time (and may be after upgrade)

**Comment by Xoius** [comment]
That didn´t helped. I gave me the permission to send commands, saved it and rebooted but if i type a command in telegram i just get the response: You are not allowed to do this

**Comment by Xoius** [comment]
Oh sry i figured it out.
But thanks for your fast response :D

**Comment by raphmeelo** [comment]
what it was?

**Comment by victor-vct** [comment]
I'm having the same problem. All permissions are right, but the message "You are not allowed to do this" keep showing. What can it be?

**Comment by derpicknicker1** [comment]
Did you follow this step from the README?

IMPORTANT
a) By clicking the pencil icon, you are able to enable/disable commands and notifications for the user/group in general. This will not affect the settings you made in 1. and 2.. It's an easy way to quickly activate/deactivate a user/group withot changing the settings. You will find the following options:

**Comment by prothinker** [comment]
I am admin of telegram group and I have all permissions but when I am trying to add new admin it shows you are not allowed to do this🙁

**Comment by heisgolden** [comment]
How did you solve this issue got a similar issue
