### ISSUE TITLE
GIF returns a blurry picture only.

### ISSUE THREAD

**Issue by MaikelKelder** [fabianonline/OctoPrint-Telegram#308]
CPU limit installed and ffmpeg, latest versions.

Everything works, only /gif and /supergif dont, the take a long time and return a blurred picture.
/status works fine, sharp picture.

No idea what to do to solve this....
Octoprint 1.4.2
Telegram 1.6.0

any pointers in the right direction are appreciated!

**Comment by giloser** [comment]
Hi,

could you please activate the debug checkbox and send a log file when you have tried to create a gif? 
Also maybe add the problematic gif and an correct image so we can see the problem?

thanks

**Comment by MaikelKelder** [comment]
[octoprint (1).log](https://github.com/fabianonline/OctoPrint-Telegram/files/5429487/octoprint.1.log)

It saves the GIF as "GIF.mp4" is that correct? cant upload it here, but noticed it when saving it as a file on my phone.
Renamed it to be able to upload it here to GIF.PNG.GIF
On my PC this plays and looks ok. in telegram its a still blurr picture, added screenshot.
![20201023_124827000_iOS](https://user-images.githubusercontent.com/37801691/97005991-77163880-153f-11eb-8d6c-ba2049b63511.png)
![PNG-afbeelding](https://user-images.githubusercontent.com/37801691/97006003-7c738300-153f-11eb-8a67-b72153bfca95.png)
![gif mp4](https://user-images.githubusercontent.com/37801691/97006041-8b5a3580-153f-11eb-9948-c7f2827ac0cf.gif)

**Comment by giloser** [comment]
hi, it doesn't work on the iphone right?
already heard that the gif don't work nicely on iphone but I have no idea why and no iphone to test that behavior ...

I'll try to think about it and found something

**Comment by MaikelKelder** [comment]
Yup, its a iphone thing!! a friend used my bot and shows GIF just fine. Closing this one...
I will leave it open to post my fix if I find it soon..... for others who suffer the same issue.

Thanks for your help Giloser!!

**Comment by MaikelKelder** [comment]
Friend of mine runs an older version of Telegram but also other things are older (octoprint, python)
Asking a gif from his printer works fine.... so its a combination of iphone/well... something on the PI..

**Comment by giloser** [comment]
Hi,

I made a change and try to test with friend with Iphone. It seems to work for them let me know if it work also for you.
You can install a test version with this link
https://github.com/giloser/OctoPrint-Telegram/archive/Fix_blurry_gif_iphone.zip
just when you are in octoprint -> options-> plugin manager -> add new -> you should have the possibility to install from an URL,
you put the https://github.com/giloser/OctoPrint-Telegram/archive/Fix_blurry_gif_iphone.zip in and install.

thanks

**Comment by MaikelKelder** [comment]
Checked.... and works!!! nice job!!
Took longer for me to test it, had a very long print going on...
Really appreciate it!
