### ISSUE TITLE
Multiple Cams text message

### ISSUE THREAD

**Issue by Vossberger** [fabianonline/OctoPrint-Telegram#313]
Actually when using multiple cams the included text message is shown up between both cam pics (cam1 - text - cam2). Is there a way to position the text After both pics are being send ? 

![158AE45C-39A3-4CC7-A2E9-6AF21299D341](https://user-images.githubusercontent.com/44831869/98725190-1a1adf00-2395-11eb-9294-514ff123b624.jpeg)

**Comment by giloser** [comment]
hi, in version 1.6.1? it's fixed image not gif then?

thanks

**Comment by Vossberger** [comment]
Hi, yes  Version 1.6.1 and fixed images, I didn't test gif.
