### ISSUE TITLE
notify on pause and resume

### ISSUE THREAD

**Issue by MarcusWolschon** [fabianonline/OctoPrint-Telegram#32]
The plugin should also allow the user to get a notification on pause and on resume.

**Comment by MiguelAngelLV** [comment]
Will it notifiy when I need change the filament?

**Comment by MarcusWolschon** [comment]
When you need to change filament, https://github.com/MarcusWolschon/UltimateFilamentSensor/ could  pause the print and this plugin would then inform you about the pause.

Octoprint-Telegram has no knowledge about how much filament you have left and that's not the job of this plugin.

**Comment by MiguelAngelLV** [comment]
I wanted to say when I used m600 code to change filament (for change color
filament). The printer pause the printing and wait.

I will want that, when the printer pause, it send my a message

**Comment by MarcusWolschon** [comment]
Ok, my patch does a Telegram-notification when Octoprint does a pause.

M600 sounds like a g-code command that makes the printer wait for you to change filament.
As far as Octoprint is concerned, that waitins is part of printing as afterwards more commands will be sent.

This sounds like a different issue and has nothing to do with the Telegram-Plugin or this specific feature-requres for the Telegram-Plugin.

**Comment by derpicknicker1** [comment]
Hey. I was quite busy the last months. Started a new job...so i had no time to work on the plugin.
Thank you @MarcusWolschon for your pull request. I'm not sure if i will integrate it. My plan is to let the user define own notification hooks on every event octoprint throws. But it will take a bit of time to integrate this. Especially the settings system (care of the the rights of users) will take some work. I think this dynamic way of adding notifications will be a better way than to hardcode more notifications. 
This topic is one of the most top items on my list. So stay tuned :)

**Comment by derpicknicker1** [comment]
Done in 1.4.0 (will come soon).

**Comment by AdmiralHawkins** [comment]
Hi, derpicknicker1, I installed your plugin, it sends me notification when print starts and when it ends but not when a m600 command occurs, even if I enabled notifications for pause event. Do I have to configure/enable something in particular to catch m600 command?
