### ISSUE TITLE
Rotated image

### ISSUE THREAD

**Issue by alasso** [fabianonline/OctoPrint-Telegram#323]
Hi, 

I have octopi configured to flip horizontally and vertically the webcam image and also rotated 90 degrees counter clockwise.
With this configuration the stream on octopi web it is Ok but in telegram the image appears rotated 180 degrees.

My installation:
Octopi Version 1.4.2
Octoprint Telegram 1.6.2

Any help will be appreciated
Adrian

![image](https://user-images.githubusercontent.com/415620/99669350-adb37600-2a4d-11eb-8a8b-705bc2cf8315.png)

![telegram-cloud-photo-size-1-5021905384775985357-x](https://user-images.githubusercontent.com/415620/99669237-89f03000-2a4d-11eb-992b-667bc17e0452.jpg)

**Comment by giloser** [comment]
Hi!

you have configured the flip in octopi (with the script file) or in octoprint (with the webconfig)?

thanks

**Comment by alasso** [comment]
Hi giloser,

I configured the flip with webconfig. 
Have I to configure it in another place?

Thanks!

![image](https://user-images.githubusercontent.com/415620/99914771-77d8f080-2cde-11eb-943c-c5c66a0a2ebb.png)

**Comment by giloser** [comment]
Hi,
no this should be good.
Could you send me a log so I can check what seems to be wrong?
thanks

**Comment by alasso** [comment]
Hi,

I resolved in a dirty way.

I edited /home/pi/oprint/lib/python2.7/site-packages/octoprint_telegram/__init__.py

At the end of take_image function I replace:
```
image = image.transpose(Image.ROTATE_270)
by
image = image.transpose(Image.ROTATE_90)
```

Do you still need the OctoPrint log file? 

Thanks a lot for your help!
Adrian

**Comment by giloser** [comment]
hi ,

glad you fix your issue but this will still be overwrite every time you update.

I still think it's not logical the option in octoprint says counter clockwise so 270 should be the correct option.
