### ISSUE TITLE
[Feature] Send timelapse after print finish

### ISSUE THREAD

**Issue by CommanderRedYT** [fabianonline/OctoPrint-Telegram#324]
Plugin would detect OctoLapse-Instance, and if turned on, would send the timelapse as mp4 after rendering is finished.

**Comment by giloser** [comment]
should be on the next release

**Comment by giloser** [comment]
#342

**Comment by cruzer619** [comment]
tried 3 different prints.. never get notified of "movie done" when print completes.  Is there any other setting needs be set besides the notification check mark?

**Comment by J3n50m4t** [comment]
How large are your timelapse Videos? If its over 20 mb nothing will Happen (See #347)

**Comment by cruzer619** [comment]
ahhh its a 23mb file.. yah just saw the thread... ok gotcha.. but thought the limit was a 50mb file but as long as its being looked at.. i'm good.. will try to make a smaller timelapse to test..

**Comment by cruzer619** [comment]
ok just made a 2.4mb timelapse and I didn't get a notification.. I have something set wrong...
