### ISSUE TITLE
Cannot read gif chart on telegram web. on mobile is ok- both on WIFI

### ISSUE THREAD

**Issue by booboo572** [fabianonline/OctoPrint-Telegram#325]
my HP and PC is connected on the same wifi at home. I can read chart on Telegram Android but not on Telegram web. What do I need to do?
![Screenshot (347)](https://user-images.githubusercontent.com/75299664/100711431-39cd8200-33ec-11eb-8563-e116d2087ee4.png)

**Comment by giloser** [comment]
Hi,

there is gif there? create with the plugin? which version of the plugin? 

I didn't use the web version as there is a windows application but as I just test it it seems to work for me.

thanks
