### ISSUE TITLE
Pre and post snapshot GCODE

### ISSUE THREAD

**Issue by sqweezr** [fabianonline/OctoPrint-Telegram#329]
I am a total noob in programming......but i was wondering if it would be possible to have a pre and post snapshot gcode (like OctoLapse) so i can turn on a strip of LEDs for the snapshot as my printer is in a dark place.

Kind regards,

Koen

**Comment by TeeVau** [comment]
I need something similar. But instead of a gcode I have to control a GPIO from the raspberry.

**Comment by sqweezr** [comment]
I am also using it to control a GPIO on the raspberry pi. I am already using it in octolapse, when the plugin makes a picture it uses a pre snapshot gcode to turn on a strip of LEDs and a post snapshot gcode to turn them off again, so it is possible.

**Comment by TeeVau** [comment]
How did you realize this? Which gcode can control a griot from raspberry? I thought that gcode is controlling the 3D printer.

**Comment by sqweezr** [comment]
Man, I am sorry. I am indeed controlling a GPIO on my Ramps 1.4 board not on the raspberry pi

**Comment by giloser** [comment]
check version 1.6.3

**Comment by sqweezr** [comment]
Thanks a lot!!! This is exactly what i was looking for. Works like a charm
