### ISSUE TITLE
PSU, remotely power on via telegram

### ISSUE THREAD

**Issue by jpokorny12** [fabianonline/OctoPrint-Telegram#330]
Good evening,
How to turn on the printer remotely via TELEGRAM add-on?
Sending custom commands does not work until the printer is connected.
Is there any way to do this?
Thank you

**Comment by db0nd** [comment]
I made psu control through the "[psu-control plugin ](url https://github.com/kantlivelong/OctoPrint-PSUControl)"https://github.com/fabianonline/OctoPrint-Telegram/pull/321 ask the author to add this feature to the release.

**Comment by jpokorny12** [comment]
Thanks :O
I add code to telegram plugin and it works 👍

**Comment by giloser** [comment]
this should be in the 1.6.3

**Comment by giloser** [comment]
#342
