### ISSUE TITLE
[Feature] Send command to terminal when issuing Messages

### ISSUE THREAD

**Issue by roboraptor** [fabianonline/OctoPrint-Telegram#331]
It would be super cool to be able to send commands like @WS_TORCH (plugin WS281x LED Status) 
to terminal before issuing taking pictures or gifs for Messages.

**Comment by giloser** [comment]
please check the version 1.6.3 to see if this work for you

**Comment by roboraptor** [comment]
I tried, and it worked! 
You are the best guys!
