### ISSUE TITLE
First time using - Refresh chat list not working 1.6.3

### ISSUE THREAD

**Issue by Canhobix** [fabianonline/OctoPrint-Telegram#341]
After adding my Telegram Bot Token, and have my connection status: Connected as "@mybotname", I'm able to test the Token and it says that the Token Status is Valid for my "mybotname".
But when I reload the chat list, nothing happens and 
![Telegram_bot_not_working](https://user-images.githubusercontent.com/43733893/107947942-63f50180-6f50-11eb-8806-a57d524ecc48.PNG)

And in the Telegram **Fabians Octoprinter Bot** I got this message: **Now I know you. Before you can do anything, go to OctoPrint Settings and edit some rights.**

Thank you so much for your support.

**Comment by giloser** [comment]
did you talk to your bot or the one from fabians? search for the @Barrxxx bot you are connected and try to talk to that one and then check again

**Comment by Canhobix** [comment]
Hello, Yes I did, I talked from my bot to fabians one vice versa.
Plz correct me if I'm wrong, but I open my bot and tried /status and also @fabianonline_octoprinter_bot to issue a /status command, and I still get the same msg,  Before you can do anything, go to OctoPrint Settings and edit some rights.

**Comment by Canhobix** [comment]
Never mind guys, my apologies, it was a browser issue, I'm using Brave and it seems that the browser tokens can't be read from the OctoPrint page because it changes to avoid being track, but I just browsed from MS Edge (chrome based) and worked.
Take care.
