### ISSUE TITLE
[Feature Request] Support for 12 Hour time formatting

### ISSUE THREAD

**Issue by Quintin9801** [fabianonline/OctoPrint-Telegram#348]
I've been using this plugin for years and I do rely on it to update me on my printers' progress, and I love it. It would be nice to have a toggle between 24h time and 12h time to display an easier reading format for those who struggle switching between the two in their head (me). This would only apply to the `{time_finish}` variable in the status updates.

For example instead of the `{time_finish}` variable outputting "13:29:37", it would output "1:29:37 pm". I have tried switching the locale to display in 12h format, but this does not apply to the plugin.

For more support of time formatting, it would be nice to include custom formatting with [strftime](https://linux.die.net/man/3/strftime) variables. This would make it easily customizable for anyone's preference.

**Comment by giloser** [comment]
I'll try to take a look if I get the time but you are welcome to create a PR with the change you would like.

**Comment by giloser** [comment]
ok I got some times , should look like that in the next release
![image](https://user-images.githubusercontent.com/12090417/109642081-d2da7900-7b52-11eb-9ce3-64d7c5ba3eb6.png)

with in the settings :
![image](https://user-images.githubusercontent.com/12090417/109642233-f998af80-7b52-11eb-9e5a-641920494c34.png)

**Comment by Quintin9801** [comment]
This is perfect! Exactly what I was hoping for, Thank you so much!
