### ISSUE TITLE
user can't modify /status message

### ISSUE THREAD

**Issue by MarcusWolschon** [fabianonline/OctoPrint-Telegram#35]
The user can modify all kinds of messages in the Octoprint settings dialog.
The status when not printing is there.
The status when printing is missing in the dialog.

**Comment by derpicknicker1** [comment]
It is the same text as defined for z-change. Do you need a seperate text for "Statuss Printing " and z-Change?

**Comment by MarcusWolschon** [comment]
Maybe it's enough to change the wording to make it obvious that "start printing" is a special case of a "z-change" in the settings dialog.

**Comment by derpicknicker1** [comment]
There allready is a hint in the stettings dialog.

![unbenannt](https://cloud.githubusercontent.com/assets/5983533/19016243/b71af946-8814-11e6-8651-c9833b74f64d.png)

**Comment by derpicknicker1** [comment]
I think this can be closed.
