### ISSUE TITLE
[Feature Request] Friendly name for Tasmota-MQTT devices ( /on /off)

### ISSUE THREAD

**Issue by SebDominguez** [fabianonline/OctoPrint-Telegram#355]
When I issue the /on or /off commands I'm prompted with a list of the Tasmoda devices's names (and they aren't really friendly)

<img width="504" alt="Capture d’écran 2021-04-21 à 10 57 39" src="https://user-images.githubusercontent.com/52816569/115526511-66494400-a290-11eb-9105-b7cd2831ece8.png">

**Comment by giloser** [comment]
well I got the name and number of relay from the plugin so if there is not an option inside the plugin I don't have any possibility to do it for now.
Maybe ask in the tasmota-mqtt plugin to add this information and then maybe I'll be able to show it.
