### ISSUE TITLE
add /resume and /pause commands

### ISSUE THREAD

**Issue by MarcusWolschon** [fabianonline/OctoPrint-Telegram#36]
It seems that I can start as print but not **/resume** it.
Neither can I **/pause** it, when I detect something is odd and want to have the printer wait until I come back to fix it without loosing the half-finished print.

Alternative **/toggle_pause** (a _printer.pause_print() and _printer.resume_print() are part of the next Octoprint release)

**Comment by MarcusWolschon** [comment]
Looks easy enough to add in
https://github.com/fabianonline/OctoPrint-Telegram/blob/master/octoprint_telegram/telegramCommands.py

according to
http://docs.octoprint.org/en/master/modules/printer.html#octoprint.printer.PrinterInterface.toggle_pause_print
there is a similar 
self.main._printer.toggle_pause_print()
command we can use.

**Comment by MarcusWolschon** [comment]
untested code:
https://github.com/MarcusWolschon/OctoPrint-Telegram/commit/9907a56b495e25846ebe3fe9668102989afdb3e7

**Comment by derpicknicker1** [comment]
Done in 1.4.0 (will come soon).

**Comment by derpicknicker1** [comment]
Done in 1.4.0 (will come soon).
