### ISSUE TITLE
Error: [ERR GET IMAGE]

### ISSUE THREAD

**Issue by Ash3781** [fabianonline/OctoPrint-Telegram#389]
I get the error [ERR GET IMAGE] in each message from the bot, everything else works but not the image, i've tried setting the snapshot address, but it still does not work: i'll add a picture of the settings
![2021-12-30_12-19 cleaned](https://user-images.githubusercontent.com/37660156/147747398-981c8cdc-cc51-4a07-a218-6dae1af5da58.png)

**Comment by Ash3781** [comment]
after a error i restarted the whole pi and the printer, and after that nothing worked anymore, so i take that "everything else works" back
![2021-12-30_14-03 cleaned](https://user-images.githubusercontent.com/37660156/147754567-a7b0c75c-f7a0-40ca-91eb-e1d4c60a9c20.png)

**Comment by giloser** [comment]
Hi ,

for the image if it doesn't work on octoprint it will not work in telegram. So first you have to made it work in test snapshot in octoprint.

for the rest send me a log so I can take a look at what is happening please.

**Comment by Ash3781** [comment]
sorry for the late reply, i just finished setting it up, i just flashed the normal octopi software onto it, instead of installing it on top of debian, it works for now, tho i need to set up the second cam and i'll probably have more question once both a re running, i'll keep you updated

**Comment by Ash3781** [comment]
apparently everything works (for now), still thanks^^
