### ISSUE TITLE
add /connect command to sys list

### ISSUE THREAD

**Issue by Raffa2s** [fabianonline/OctoPrint-Telegram#40]
can you add /connect command to sys list, so we can connect the printer to the raspberry (running octoprint) trought telegram?
thanks

**Comment by Raffa2s** [comment]
double iusse

**Comment by derpicknicker1** [comment]
Hint: `/sys` is only for System-Commands you defined in `config.yaml`
See http://docs.octoprint.org/en/master/configuration/config_yaml.html#system
