### ISSUE TITLE
upgrading to 1.10.0 - files and print command fail with list_files() got an unexpected keyword argument 'destinations'

### ISSUE THREAD

**Issue by guysoft** [fabianonline/OctoPrint-Telegram#424]
Hey,
Recently upgraded to OctoPrint 1.10.0 , and now when I run ``/print`` or ``/files`` I get in Octoprint.log:
```
2024-05-02 20:38:35,252 - octoprint.plugins.telegram.TCMD - ERROR - An Exception in fileList : list_files() got an unexpected keyword argument 'destinations'
```
Thats it, no other error.
Telegram hangs on "loading files"

**Comment by stedaho** [comment]
I can confirm that. Upgraded to OctoPrint 1.10.0 yesterday and now getting the same exception when trying to list files/start print. So no printing via telegram is possible at the moment! 
Telegram Notifications v 1.6.5

**Comment by guysoft** [comment]
Ok, got a fix

**Comment by guysoft** [comment]
https://github.com/fabianonline/OctoPrint-Telegram/pull/425/

You can install and test here:
https://github.com/guysoft/OctoPrint-Telegram/archive/refs/heads/bugfix/424.zip

**Comment by stedaho** [comment]
Thanks a lot, I will try and give feedback here once my current long-running print has been finished!

**Comment by stedaho** [comment]
I just tried your patch and I can confirm that it is working like a charm!
