### ISSUE TITLE
Faulty status after connect

### ISSUE THREAD

**Issue by derSkimmy** [fabianonline/OctoPrint-Telegram#5]
If connecting to an active octoprint-session, and going up 10mm on Z without homing, the bot automatically messages:

`Printing at Z=-10.0.
Bed 26.0/0.0, Extruder 21.9/0.0.
00:00:00, 0% done, 00:00:00 remaining.`

While all messages are customized to german language, this message is probably somewhere hardcoded and a little bit missleading.

**Comment by fabianonline** [comment]
It was definitely a bug that you got a message. That should only happen on ZChange events *during* printing.
The message is the default ZChange message ("Message at new height"). Did you customize these as well?

**Comment by derSkimmy** [comment]
Yeah, it is all customized to the german counterparts.

**Comment by fabianonline** [comment]
Okay, after updating the plugin you'll have to set the ZChange message again, but then it will be used. ;-)
