### ISSUE TITLE
Edit user Command or Notify

### ISSUE THREAD

**Issue by temuccio** [fabianonline/OctoPrint-Telegram#50]
Hello, 
when I set authorization on one user pressing pencil, 
I have this error (on inspect element of Chrome):
Uncaught TypeError: Unable to process binding "checked: function (){return settings.settings.plugins.telegram.chats['269074525']
Do you can help me

**Comment by derpicknicker1** [comment]
Are you using chrome?
This seems to be a problem with chrome caching the settings data. Try to clear your website cache and relaod the page (while you are logged in). I try to solve it. Also i will inform Gina (Dev of Octoprint) because i think it is a problem within octoprint.

**Comment by derpicknicker1** [comment]
I reportet this potential bug(https://github.com/foosel/OctoPrint/issues/1567)
Maybe you can test in other browsers? For me it worked wit IE.
