### ISSUE TITLE
Nothing append when i click "pencil" user icon

### ISSUE THREAD

**Issue by Nitrosito** [fabianonline/OctoPrint-Telegram#54]
Hi,

I have a Token valid for my bot (status appear in greend and ok)
I send a message to bot, chat appear in the list, but if i click on pencil, nothing happend. i cant check boxes.

I use Firefox,

Regards

**Comment by Nitrosito** [comment]
I update to octoprint 1.2.18 and fix. 

Maybe dont work after, because i connect to print

#FIX #close

**Comment by derpicknicker1** [comment]
Should be fixed by merging #52
