### ISSUE TITLE
Webcam image has the wrong orientation

### ISSUE THREAD

**Issue by kevinrombach** [fabianonline/OctoPrint-Telegram#57]
The image sent from the bot has another orientation like the stream in the control tab when i change the orientation of the webcam in the octoprint settings. How can i fix that?

**Comment by derpicknicker1** [comment]
The plugin uses the settings you make for the webcam in Octoprint. So the image should be rotated/flipped as you set it in the webcam settings. I can not reproduce this issue.

**Comment by derpicknicker1** [comment]
This should not happen. I will check this again.

**Comment by derpicknicker1** [comment]
I found the issue. Telegram bot rotates the images 90° clockwise. OctoPrint does this counter clockwise (as the option in webcam settings tell). Will be fixed in next update.

**Comment by derpicknicker1** [comment]
Still some issues :disappointed:

**Comment by NiklasOlofsson** [comment]
Getting upside down picture in Telegram with the latest release. I have "Rotate webcam 90 degrees counter clockwise" enabled.

**Comment by Sunoo** [comment]
I'm also getting upside down pictures in Telegram with the camera rotated 90 degrees in Octoprint.

**Comment by OdomLinx** [comment]
I have the same problem too.

**Comment by kaju666** [comment]
Any updates, problem still exist.

**Comment by Guduche** [comment]
I have the same problem too

**Comment by GilDev** [comment]
Same problem… Image flipped 180°… ☹️

**Comment by carlosgalvezp** [comment]
Same problem here with latest release. I had to spend quite some time playing with the different rotations in Octoprint to end up getting a straight image in Telegram. But of course now the image in Octoprint is flipped...

**Comment by Vabe7** [comment]
I also have this issue, the image is flipped...

**Comment by giloser** [comment]
Hi,
to be sure I understand this correctly you didn't change the rotation in the \boot\octopi.txt file but in the interface of Octoprint? And then it's not correct between octoprint and telegram?
I change my config in the file so I flipped the image before octoprint create the stream and I don't have to change it to have it correct in telegram.

**Comment by th3darkang3l** [comment]
I found a workaround and fixed locally this problem... the issue is that whatever rotation CW or CCW you have the plugin do always the same rotation (this line of code https://github.com/fabianonline/OctoPrint-Telegram/blob/b1f90950293575005d3be4d791602a662222a366/octoprint_telegram/__init__.py#L1321 )

I beg some collaborator to fix the issues managing the two types of rotation, in the meantime to fix the issues locally you can : 
- putty/ssh into your box
- nano/vi /oprint/lib/python2.7/site-packages/octoprint_telegram/__init__.py
- find ROTATE_270 and change to ROTATE_90
- save and reboot
Now images that are sent to your telegram bot are no longer upside down.

**Comment by danst0** [comment]
Still open

**Comment by axelschmidt91** [comment]
I get the same problem. Is it possible to reopen this issue?

**Comment by giloser** [comment]
Like I said on the #287 I'll will on the next release add an option to rotate on 270 or 90° so you could choose the best for you.

**Comment by alakond** [comment]
> I found a workaround and fixed locally this problem... the issue is that whatever rotation CW or CCW you have the plugin do always the same rotation (this line of code
> 
> https://github.com/fabianonline/OctoPrint-Telegram/blob/b1f90950293575005d3be4d791602a662222a366/octoprint_telegram/__init__.py#L1321
> 
> )
> I beg some collaborator to fix the issues managing the two types of rotation, in the meantime to fix the issues locally you can :
> 
> * putty/ssh into your box
> * nano/vi /oprint/lib/python2.7/site-packages/octoprint_telegram/__init__.py
> * find ROTATE_270 and change to ROTATE_90
> * save and reboot
>   Now images that are sent to your telegram bot are no longer upside down.

Didn't help. Doesn't work. Any other ideas?
