### ISSUE TITLE
"Shutdown" not available after octoprint 1.3 upgrade

### ISSUE THREAD

**Issue by pieri70** [fabianonline/OctoPrint-Telegram#60]
Hello
I use this plugin often to control my printer when I'm away from my printer room
When I mwas with the previous version of octorpint under /sys options there were shutdown (and reboot if I remember well)
Now these commands are not available..
What happened?
I tried many oprions and I reinstalled Octoprint completely..

Is there some option I must add to config.yaml?

Thanks!
Pietro

**Comment by papinist** [comment]
Same here. I have some custom commands in my config.yaml and using \sys I get the prompt with these custom commands, but the system commands (shutdown system, reboot system and restart octoprint) are missing.
