### ISSUE TITLE
Flip webcam doesn't have effect

### ISSUE THREAD

**Issue by darkom-ltu** [fabianonline/OctoPrint-Telegram#72]
Hello,

I have the following problem, I set up a webcam with my OctoPi and I had to rotate it and flip it vertically and horizontally. On the web, server image looks correct, but on telegram is upside down. It looks like it is only doing rotation 90 degrees but doesn't flip an image. 

Is there any solution for such problem?

**Comment by NiklasOlofsson** [comment]
Same here.

**Comment by jkronen** [comment]
Why is this closed? I have the same problem

**Comment by derpicknicker1** [comment]
Solution will come. I have to do an update but dont have time for it. Sorry. Stay tuned.

**Comment by userosos** [comment]
It not work now, please update! How we can make it plugin from source? Does anyone have an instruction for make it from source?

**Comment by kaju666** [comment]
Any bugfix for that?

**Comment by b0b0x** [comment]
Hi, same issue... could you please fix it?

The plugin is rotating clockwise instead of counterclockwise setting in octoprint, Then the telegram picture is always upside down compared to the webcam image in octoprint...

**Comment by kaju666** [comment]
@b0b0x i started using octoslack, and its very good for notofications

**Comment by rlogiacco** [comment]
Let's merge the discussion on issue #146 : we have applied a pull request which should have this fixed, but we need feedback
