### ISSUE TITLE
Error: 'NoneType' object has no attribute 'username'

### ISSUE THREAD

**Issue by ido1990** [fabianonline/OctoPrint-Telegram#73]
Hi!
I installed the plugin couple days ago and it worked.
Suddenly it stopped and shows an error:
Error: 'NoneType' object has no attribute 'username'
Screenshot:
[https://i.imgsafe.org/afaae87715.png](https://i.imgsafe.org/afaae87715.png)

Tried to disable and enable the plugin but it didn't solve it.

Thanks!

**Comment by PaulsPi** [comment]
Hey, i got the same problem! Did you already solve it?

**Comment by ido1990** [comment]
No... 
I changed the token from the botfather and it temporarily fixed but it's back again. Also the bot stopped responding even if the token is working.. .

**Comment by PaulsPi** [comment]
I guess it has something to do with the TouchUI plugin... I've been deleting the whole raspberry and booting it again, installing telegram and many other plugins. After installing the TouchUI plugin and the autostart of it the telegram plugin showed the same error as before.

**Comment by ido1990** [comment]
Hmm,
I just uninstalled TouchUI but it didn't fix it.
I get this error on the log:
ERROR - Exception caught! 'NoneType' object has no attribute 'commandDict'

**Comment by derpicknicker1** [comment]
That sounds strange. May you please enable debug option of plugin, try to reproduce the error and upload the octoprint.log to http://gist.github.com or somewhere else?

**Comment by yorambi** [comment]
this may related to that in cmdSys @derpicknicker1 hard coded the system commands.
in windows install those do not exist by default and if added, they just being duplicated in the Telegram view. 

this should be removed from telegramCommands.py:

   `keys.append([["Restart OctoPrint","/sys_sys_Restart OctoPrint"]])`
   `keys.append([["Reboot System","/sys_sys_Reboot System"],["Shutdown System","/sys_sys_Shutdown System"]])`

this re-added:
`if empty: message += "\n\n"+self.gEmo('warning')+" No System Commands found..."`

as in v1.4.1 and same as in cmdCtrl

**Comment by ir-fuel** [comment]
Same error here, same plugins installed. Going to try disabling some.

**Comment by ir-fuel** [comment]
And yes, removing the room temperature plugin solved the issue
