### ISSUE TITLE
Timelapse files support

### ISSUE THREAD

**Issue by funkycode** [fabianonline/OctoPrint-Telegram#75]
I would like to request the feature to get timelapse files via chat commands.
I'll try to see if I can implement it by myself and PR, but as I'm not familiuar with OctoPi or Telegram APIs if I would be able to do it in short time period.
Thanks

**Comment by derpicknicker1** [comment]
I have this on my list, but telegram does not support the video format of the timelapses. I figured out a command to properly convert them to use with telegram but i did not do further tests until now.

**Comment by DaAwesomeP** [comment]
@derpicknicker1 For me, it would be fine if they were just available as downloads to view with another app (ex. VLC). At least please make it an option to download the original file; I'm not sure how well my OctoPrint machine will be able to re-encode the videos on the fly.

**Comment by DeastinY** [comment]
Agreed. Just receiving the file would be amazing ❤️

**Comment by danhae** [comment]
Hi, i would love to have this feature as well.
Maybe it is a solution to send it as a gif-file?
After the timelapse-video is finished, the plugin make it to a gif
`ffmpeg -ss 30 -t 3 -i input.mp4 -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 output.gif` and send it via telegram.
Maybe it is a solution?

**Comment by TheAndi** [comment]
Any news on that?
This feature would be awesome!

Thanks in advance
