### ISSUE TITLE
Number of requests

### ISSUE THREAD

**Issue by MichMich** [fabianonline/OctoPrint-Telegram#77]
First of all: awesome plugin! Thank you very much for your hard work.

As a user of [PiHole](http://pi-hole.net) I've started to notice the amount of network calls this plugin does. It turns out the 20% of ALL my DNS requests my network (all devices included) are DNS requests for api.telegram.org coming from my OctoPi. 

It hasn't been any issue so far, but it might be worth looking into, considering my Printer is mostly idle. But it might be interesting to throttle the number of request (when the printer is idle).

Keep up the great work!

**Comment by derpicknicker1** [comment]
the bot calls the api every 30 seconds. This is necessary to get messages . The connection is held open for 30 seconds but then has to be reestablished to circumvent a timeout.
