### ISSUE TITLE
compatibility with OctoPrint PSU Control

### ISSUE THREAD

**Issue by leobel96** [fabianonline/OctoPrint-Telegram#81]
Could you please add the possibility to switch on/off the printer adding the compatibility with OctoPrint PSU Control plugin (https://github.com/kantlivelong/OctoPrint-PSUControl/blob/master/README.md)? I think that adding the options in /sys should be perfect.

**Comment by derpicknicker1** [comment]
The PSU Control plugin has no helper methods defined for use by other plugins.

**Comment by leobel96** [comment]
So there is no possibility to switch on/off printer from telegram bot? What about the integration with other plugins that permit the relay control such as "Octoprint-enclosure" plugin?

**Comment by derpicknicker1** [comment]
You may define own system commands (which e.g. call ascript). They will appear in /sys

**Comment by leobel96** [comment]
Ok. Thank you
