### ISSUE TITLE
Error of notifications

### ISSUE THREAD

**Issue by garremmash** [fabianonline/OctoPrint-Telegram#93]
Here is such problems

ERROR: I was not able to format the Notification for 'PrinterStart' properly. Please open your OctoPrint settings for Telegram Notifications and check message settings for 'PrinterStart'.

ERROR: I was not able to format the Notification for 'PrinterShutdown' properly. Please open your OctoPrint settings for Telegram Notifications and check message settings for 'PrinterShutdown'.

But on the settings everything is ok.

**Comment by derpicknicker1** [comment]
Please post the message text from the settings.

**Comment by Evg33** [comment]
`{emo:octo} {emo:shutdown} Shutting down. Goodbye.`

`{emo:rocket} Hello. I'm online and ready to receive your commands.`

**Comment by CapXilinx** [comment]
I have the same issue. It seems that this problem is related to the used emotes. When I deactivate the emotes the message are Sent correctly.

**Comment by thesourcerer** [comment]
Got the same problem with "PrinterStart" after upgrading OctoPrint today to latest 1.3.11

**Comment by miblafi** [comment]
Had the same issue, I disabled the Emojis and the message was successfully sent, as CapXilinx did

**Comment by Evg33** [comment]
After Octoprint upgrade to 1.3.11 telegram plugin is unable to format emo:rocket and other emos #174

**Comment by pokono** [comment]
+1

**Comment by rpetteruti** [comment]
+1

**Comment by khseal** [comment]
+1

**Comment by MartinRohrbach** [comment]
+1

**Comment by gmccauley** [comment]
+1

**Comment by Budavaril** [comment]
Using no space or at least 2 spaces between rocket emo and the text. With 1 spaces will give error.

**Comment by kverbeeck** [comment]
> Using no space or at least 2 spaces between rocket emo and the text. With 1 spaces will give error.

Thanks man, great workaround.

**Comment by rlogiacco** [comment]
This has been fixed in the current master branch and will be delivered with the next release.
