### ISSUE TITLE
[Feature Request] Command for Run Shell Script

### ISSUE THREAD

**Issue by clihlt** [fabianonline/OctoPrint-Telegram#94]
It would be nice if there was a command for calling a custom script. For example, de-energize the relay printer or workshop where it stands. Turn on and off the light above the table or something like that. The implementation of each will have its own, depending on the hardware. But if in the bot will be the ability to run their scripts through bot commands, then it will be fine. 5-6 user commands, at least.

/usercmd1 
/usercmd2 
etc...

**Comment by derpicknicker1** [comment]
You can run scripts via system commands defined in octoprint.
