### ISSUE TITLE
[Feature request] Support multiple octoprint instances

### ISSUE THREAD

**Issue by ir-fuel** [fabianonline/OctoPrint-Telegram#97]
If I reuse the same token on different instances I get a 409. It seems I need to make a bot for each instance?

**Comment by derpicknicker1** [comment]
It is not possible to reuse the bot token on multiple instances of octoprint.. 
When you reuse it, only one of the instances will get the command and you dont know which it would be. So it is not possible to implement this.

Okay it will be, when you run a bot just in one instance and relay the commands to the other instances. But that will be a hell to implement. And the commands will need to have an id to let the bot know which instance should be triggered. Something like _/status@printer1_. This will make sending commands much more complicated.

So no, this would not be a feature in the near future.
